apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-defaultconf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /product {
        proxy_pass http://product/;
      }

      location /order {
        proxy_pass http://order/;
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>Simple</title></head>
      <body>
        <h1>Hello from NGINX!</h1>
        <p><a href="/products">Product Service</a></p>
        <p><a href="/orders">Order Service</a></p>
        <h1>Frontend connected to Product + Order</h1>
      </body>
    </html>