galaxy_info:
  role_name: install_docker
  author: Your Name
  description: Install Docker and required Python libraries on Debian/Ubuntu hosts.
  license: MIT
  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - docker
    - install
    - system
    - ansible_role

dependencies: []
