---
# tasks file for install-docker
 - name: update apt
   apt:
    update_cache: yes

 - name: install pre-requists
   apt:
    name:
     - ca-certificates 
     - curl
    state: present

 - name: Create a directory 
   ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

 - name: Download docker gpg
   ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

 - name: add apt repo
   apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: /etc/apt/sources.list.d/docker.list
     

 - name: re-update apt 
   apt:
    update_cache: yes

 - name: install docker
   apt:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd.io 
     - docker-buildx-plugin
     - docker-compose-plugin
    state: present

 - name: Restart Docker 
   service: 
    name: docker
    state: started 

 - name: Add user to the docker group
   user:
    name: "{{ ansible_user_id }}"
    group: docker
    append: yes