galaxy_info:
  role_name: simple_nginx
  author: Mahmoud Mansour 
  description: >
    An Ansible role to build a custom Nginx Docker image and run a container.
  license: MIT
  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - 7
        - 8

  galaxy_tags:
    - docker
    - nginx
    - container
    - webserver
    - ansible_role

dependencies: []
